# Generated by Django 4.0.3 on 2022-04-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('types', models.CharField(choices=[('1-kishilik', '1-kishilik'), ('2-kishilik', '2-kishilik'), ('3-kishilik', '3-kishilik'), ('4-kishilik', '4-kishilik'), ('5-kishilik', '5-kishilik')], max_length=11)),
                ('bandligi', models.CharField(choices=[('YES', 'NO'), ('YES', 'NO')], max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='yulduzlar_soni',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('1', '1'), ('4', '4'), ('5', '5')], max_length=2),
        ),
        migrations.CreateModel(
            name='Ijara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ijaraga_olinadigan_kun', models.DateTimeField()),
                ('ijaradan_chiqadigan_kun', models.DateTimeField()),
                ('person_qty', models.CharField(choices=[('1-kishilik', '1-kishilik'), ('2-kishilik', '2-kishilik'), ('3-kishilik', '3-kishilik'), ('4-kishilik', '4-kishilik'), ('5-kishilik', '5-kishilik')], max_length=11)),
                ('ijarachi', models.CharField(max_length=100)),
                ('passport_serias', models.CharField(max_length=9)),
                ('room_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.room')),
            ],
        ),
    ]
