# Generated by Django 4.0.3 on 2022-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_room_alter_hotel_yulduzlar_soni_ijara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='yulduzlar_soni',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=2),
        ),
    ]
