# Generated by Django 4.0.3 on 2022-04-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_hotel_yulduzlar_soni_alter_room_bandligi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='yulduzlar_soni',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('4', '4'), ('5', '5'), ('1', '1')], max_length=2),
        ),
    ]
