# Generated by Django 4.0.3 on 2022-04-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_hotel_yulduzlar_soni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(height_field=100, upload_to='images/', width_field=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='yulduzlar_soni',
            field=models.CharField(choices=[('5', '5'), ('3', '3'), ('2', '2'), ('4', '4'), ('1', '1')], max_length=2),
        ),
    ]
